# Generated by Django 4.2.3 on 2023-07-18 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='varieties',
            name='control',
        ),
        migrations.RemoveField(
            model_name='varieties',
            name='pest',
        ),
        migrations.CreateModel(
            name='pest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('varieties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.varieties')),
            ],
        ),
        migrations.CreateModel(
            name='control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.varieties')),
            ],
        ),
    ]
