# Generated by Django 4.2.3 on 2023-07-18 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_varieties_control_remove_varieties_pest_pest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='pest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.pest'),
        ),
    ]
