# Generated by Django 4.2.3 on 2023-07-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_productcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='varieties',
            name='category_var',
            field=models.CharField(default='chicken', max_length=100),
        ),
    ]
