# Generated by Django 4.2.3 on 2023-07-19 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_varieties_category_var'),
    ]

    operations = [
        migrations.CreateModel(
            name='treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='pest',
            new_name='disease',
        ),
        migrations.DeleteModel(
            name='control',
        ),
        migrations.AddField(
            model_name='treatment',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.disease'),
        ),
    ]
