# Generated by Django 4.2.3 on 2023-07-19 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_treatment_rename_pest_disease_delete_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='pest_description',
            field=models.TextField(default='i'),
        ),
        migrations.CreateModel(
            name='symptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.disease')),
            ],
        ),
    ]
