# Generated by Django 4.2.3 on 2023-07-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_disease_pest_description_symptoms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptoms',
            old_name='method',
            new_name='sym',
        ),
        migrations.AddField(
            model_name='symptoms',
            name='treatment',
            field=models.TextField(default='salt lick'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='treatment',
        ),
    ]
