# Generated by Django 4.2.3 on 2023-07-20 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_rename_method_symptoms_sym_symptoms_treatment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dis', to='App.disease'),
        ),
    ]
