# Generated by Django 4.2.3 on 2023-07-21 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_cropcategory_cropvarieties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropvarieties',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.cropcategory'),
        ),
    ]
