# Generated by Django 4.2.3 on 2023-07-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_cropvarieties_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropvarieties',
            name='weather',
            field=models.TextField(),
        ),
    ]
