# Generated by Django 4.2.3 on 2023-08-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_alter_category_image_alter_cropcategory_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disease_description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.TextField()),
                ('controls', models.TextField()),
                ('varieties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.varieties')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='controls',
            field=models.TextField(default='hi'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(default='hi'),
        ),
        migrations.DeleteModel(
            name='symptoms',
        ),
    ]
