# Generated by Django 4.2.3 on 2023-08-30 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_remove_cropvarieties_small_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='controls',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='symptoms',
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_sym', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.disease')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_con', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.symptom')),
            ],
        ),
    ]
