# Generated by Django 4.2.3 on 2023-08-30 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_remove_disease_controls_remove_disease_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.disease'),
        ),
    ]
